monorepo_root = true

[tools]
node = "22"
python = "3.12"
uv = "latest"

[env]
NATS_URL = "nats://localhost:4222"
NATS_HOST_PORT = "4222"

[monorepo]
config_roots = [
    "packages/*"
]

[tasks.bootstrap]
description = "Install project dependencies"
run = "mise //packages/...:bootstrap"

[tasks.codecheck]
description = "Run all code checks"
run = "mise //packages/...:codecheck"

[tasks.format]
description = "Run formatting"
run = "mise //packages/...:format"

# NATS
[tasks.nats-start]
description = "Run the NATS server using docker"
usage = '''
flag "--profile <profile>" {
    help "Docker compose profile"
    choices "debug" "none"
    default "debug"
}
'''
run = "docker compose --profile ${usage_profile?} -f docker-compose/nats.yaml up -d"

[tasks.nats-stop]
description = "Stops the NATS server"
run = "docker compose -f docker-compose/nats.yaml down"